version: 0.0
os: linux
files:
  - source: /src
    destination: /var/www
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 600
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 600
      runas: root
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 600